---
name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - name: "DB Deployment"
        run: echo "Running..."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run npm and install dependencies
        run: |
          npm update -g npm
          npm install -g wrangler

      - name: Deploy
        run: npx wrangler d1 execute trainingday --file="./db/schema.sql"

  workers:
    strategy:
      fail-fast: false
      matrix:
        worker: ["list", "get"]
    runs-on: ubuntu-latest
    steps:
      - name: "${{ matrix.worker }} Deployment"
        run: echo "Running..."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update npm, install dependencies of worker
        run: npm update -g npm

      - name: Build
        run: |
          cd ./${{ matrix.worker }}
          npm ci

      - name: Run tests
        run: |
          cd ./${{ matrix.worker }}
          npm test

      - name: Deploy (dry run)
        run: |
          cd ./${{ matrix.worker }}
          npm dry-run

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./${{ matrix.worker }}
          npm deploy
